In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Consumer_Complaints.csv")

C:\Users\Ruhi\Anaconda3_new\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,07/11/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,NAVY FEDERAL CREDIT UNION,MO,NaN,NaN,NaN,Web,07/11/2019,In progress,Yes,NaN,3303029
1,07/11/2019,Debt collection,Other debt,Attempts to collect debt not owed,Debt is not yours,NaN,Company can't verify or dispute the facts in t...,"CCS Financial Services, Inc.",AR,71747,NaN,NaN,Web,07/11/2019,Closed with explanation,Yes,NaN,3303081
2,07/11/2019,Debt collection,Other debt,Attempts to collect debt not owed,Debt was result of identity theft,NaN,NaN,"Diversified Consultants, Inc.",GA,30083,NaN,NaN,Web,07/11/2019,In progress,Yes,NaN,3302734
3,07/11/2019,"Payday loan, title loan, or personal loan",Installment loan,Getting the loan,NaN,NaN,NaN,NAVY FEDERAL CREDIT UNION,VA,230XX,Servicemember,NaN,Web,07/11/2019,In progress,Yes,NaN,3303054
4,07/11/2019,Debt collection,Other debt,Written notification about debt,Didn't receive enough information to verify debt,NaN,NaN,"EOS Holdings, Inc.",IN,NaN,NaN,NaN,Web,07/11/2019,Closed with explanation,Yes,NaN,3303406

In [140]:
copy_df = df
df=df[["Product","Consumer complaint narrative"]]

In [141]:
df["Product"]=df["Product"].str.lower()
df["Product"].value_counts()

C:\Users\Ruhi\Anaconda3_new\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

mortgage                                                                        281989
debt collection                                                                 253130
credit reporting, credit repair services, or other personal consumer reports    249750
credit reporting                                                                140432
credit card                                                                      89190
bank account or service                                                          86206
student loan                                                                     52791
credit card or prepaid card                                                      52093
checking or savings account                                                      44706
consumer loan                                                                    31605
vehicle loan or lease                                                            12322
money transfer, virtual currency, or money service                               11096
payday loan, title loan, or personal loan                                         9330
payday loan                                                                       5544
money transfers                                                                   5354
prepaid card                                                                      3819
other financial service                                                           1059
virtual currency                                                                    18
Name: Product, dtype: int64

In [142]:
df.isnull().sum()

Product                              0
Consumer complaint narrative    935070
dtype: int64

In [143]:
df.head()

,Product,Consumer complaint narrative
0,"credit reporting, credit repair services, or o...",NaN
1,debt collection,NaN
2,debt collection,NaN
3,"payday loan, title loan, or personal loan",NaN
4,debt collection,NaN

In [144]:
df=df.dropna()

In [145]:
df.shape

(395364, 2)

In [146]:
df.isnull().sum()

Product                         0
Consumer complaint narrative    0
dtype: int64

In [147]:
df["Product"].value_counts()

credit reporting, credit repair services, or other personal consumer reports    97387
debt collection                                                                 89119
mortgage                                                                        53993
credit reporting                                                                31588
credit card or prepaid card                                                     22684
student loan                                                                    22345
credit card                                                                     18838
bank account or service                                                         14885
checking or savings account                                                     13602
consumer loan                                                                    9474
vehicle loan or lease                                                            6045
money transfer, virtual currency, or money service                               5728
payday loan, title loan, or personal loan                                        4674
payday loan                                                                      1747
money transfers                                                                  1497
prepaid card                                                                     1450
other financial service                                                           292
virtual currency                                                                   16
Name: Product, dtype: int64

In [148]:
def renaming(x):
    if x =='credit reporting':
        x = 'credit reporting, credit repair services, or other personal consumer reports'
    elif x == 'credit card':
        x = 'credit card or prepaid card'
    elif x == 'virtual currency':
        x = 'money transfer, virtual currency, or money service'
    elif x == 'prepaid card':
        x = 'credit card or prepaid card'
    elif x == 'money transfers':
        x = 'money transfer, virtual currency, or money service'
    elif x=='consumer loan' or x=='payday loan' or x=='payday loan, title loan, or personal loan' or x=='student loan' or x=='vehicle loan or lease':
        x='loan'
    elif x=='checking or savings account':
        x='bank account or service'
    return x

In [149]:
df["Product"]=df["Product"].apply(renaming)

In [150]:
df.shape

(395364, 2)

In [151]:
df["Product"].value_counts()

credit reporting, credit repair services, or other personal consumer reports    128975
debt collection                                                                  89119
mortgage                                                                         53993
loan                                                                             44285
credit card or prepaid card                                                      42972
bank account or service                                                          28487
money transfer, virtual currency, or money service                                7241
other financial service                                                            292
Name: Product, dtype: int64

In [152]:
index=df["Product"]!="money transfer, virtual currency, or money service"

In [153]:
df=df[index]

In [154]:
df["Product"].value_counts()

credit reporting, credit repair services, or other personal consumer reports    128975
debt collection                                                                  89119
mortgage                                                                         53993
loan                                                                             44285
credit card or prepaid card                                                      42972
bank account or service                                                          28487
other financial service                                                            292
Name: Product, dtype: int64

In [155]:
index=df["Product"]!="other financial service"

In [156]:
df=df[index]

In [157]:
df.shape

(387831, 2)

In [158]:
df.head()

,Product,Consumer complaint narrative
43374,debt collection,When they call they dont answer the call and t...
44383,"credit reporting, credit repair services, or o...",XXXX XXXX XXXX XXXX had posted 3 collection ac...
44469,bank account or service,XXXX of the month every month since XX/XX/2019...
44562,debt collection,There are 2 charges on my credit report from a...
44659,debt collection,I provided account information which showed de...

In [159]:
from sklearn.preprocessing import LabelEncoder

In [160]:
label=LabelEncoder()

In [161]:
df["Product"]=label.fit_transform(df["Product"])

In [162]:
df.shape

(387831, 2)

In [163]:
df=df.iloc[0:5001,:]
corpus=df["Consumer complaint narrative"].str.lower().tolist()

In [164]:
df

       Product                       Consumer complaint narrative
43374        3  When they call they dont answer the call and t...
44383        2  XXXX XXXX XXXX XXXX had posted 3 collection ac...
44469        0  XXXX of the month every month since XX/XX/2019...
44562        3  There are 2 charges on my credit report from a...
44659        3  I provided account information which showed de...
45284        2  XX/XX/2018 I filed a dispute through credit ka...
45331        3  I have visited XXXX XXXX XXXX XXXX XXXX for an...
45661        3  Today I recieved a letter for Kent hollins for...
45782        2  AFTER REVIEWING MY CREDIT REPORT, I HAVE IDENT...
45979        3  Commonwealth Financial, located at XXXX XXXX X...
45984        2  One main financial obtained a copy of my credi...
45987        2  AFTER REVIEWING MY CREDIT REPORT, I HAVE IDENT...
46246        2  Accurately I am ask the credit bureaus to repo...
46262        2  AFTER REVIEWING MY CREDIT REPORT, I HAVE IDENT...
46535        3  I received a call from this person claiming to...
46700        3  Synergetic Communications , Inc. Say that they...
46865        5  Mr. Cooper purchased our home loan from our or...
47053        2  XXXX has reported my score incorrectly, becaus...
48276        2  This people are rude below is the paperwork of...
49253        2  ( a ) Block. Except as otherwise provided in t...
49321        2  The following accounts are fraudulent XXXX {$1...
49412        2  I XXXX XXXX notice that XXXX and XXXX  continu...
50006        2  I am writing to request the removal of unautho...
50017        2  After sending information to verify myself wit...
50147        2  My Identity has been compromised and misused f...
50222        2  These fraudulent accounts are reporting on my ...
50419        2  Im a victim of Transunion inquiry issues. I ha...
50458        2  To whom this may concern : This complaint is d...
50491        2  These fraudulent accounts are reporting on my ...
50724        2  My identity was compromised while I was overse...
...        ...                                                ...
77212        2  Transunion, XXXX, XXXX all show inquiries to b...
77214        4  On XX/XX/XXXX, a lease agreement for XXXX XXXX...
77216        5  My mortgage payment is XXXX per month. I paid ...
77220        4  I have been a customer with credit central for...
77224        3  XXXX XXXX , XXXX collection agency keeps calli...
77228        3  At the time that I received this bail bond I w...
77234        2  ONCE AGAIN XXXX  DELETED BK PUPLIC RCORDS WITH...
77236        1  On XX/XX/2019 I requested made an online credi...
77238        1  On XX/XX/19, we paid off the balances on our c...
77240        2  XXXX XXXX XX/XX/XXXX {$9700.00} XXXX XXXX XX/X...
77242        2  I need to get my name straight on my credit re...
77244        0  BMO Harris will return my check and charge {$3...
77246        4  Hello, I believe that I was victim to a fraudu...
77250        1  Chase has allowed merchants using cards that w...
77254        2  This is a writter request to block information...
77258        2  I contacted Nelnet In XXXX regarding my past d...
77270        5  In XX/XX/XXXX I purchased a property in XXXX t...
77274        3  I received notification that this debt that wa...
77280        2  i took out a loan against my house with citifi...
77282        1  I opened a citi doublecash card with a 0 % pro...
77284        5  The problem hasn't quite occurred yet, but I'm...
77286        2                                     identity theft
77288        2  XXXX ONCE AGAIN HAS VIOLATED THE FCRA, FALSELY...
77290        2  I have a XXXX XXXX credit card that I have nev...
77296        2  On XX/XX/XXXX, I attempted to place a temporar...
77298        3  FCRA states information reporting has to be 10...
77306        2  On XXXX/XXXX I submitted certified letters to ...
77308        2  This is a writter request to block information...
77316        3  i was XXXX at the time of this school being at...
77322        0  My name is XXXX XXXX i tried to close my check...

[5001 rows x 2 columns]

In [165]:
from nltk.corpus import stopwords
from string import punctuation

In [166]:
stuff_to_be_removed=list(stopwords.words("english"))+list(punctuation)

In [167]:
from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer

In [168]:
stemmer=LancasterStemmer()

In [169]:
final_corpus=[]
for i in range(len(corpus)):
    word=word_tokenize(corpus[i])
    word=[stemmer.stem(t) for t in word if t not in stuff_to_be_removed]
    word=" ".join(word)
    final_corpus.append(word)

In [181]:
df["Clenaed complaines"]=final_corpus

In [183]:
new_df=df.iloc[:,[0,2]]
new_df

       Product                                 Clenaed complaines
43374        3  cal dont answ cal cal day long hav sign contac...
44383        2  xxxx xxxx xxxx xxxx post 3 collect account 3 c...
44469        0  xxxx mon every mon sint xx/xx/2019 've reciev ...
44562        3  2 charg credit report collect ag `` trid asset...
44659        3  provid account inform show debt paid credit ka...
45284        2  xx/xx/2018 fil disput credit karm fil anoth di...
45331        3  visit xxxx xxxx xxxx xxxx xxxx il 2016 bil amo...
45661        3  today reciev let kent hollin account xxxx xxxx...
45782        2  review credit report ident inacc account unaw ...
45979        3  commonweal fin loc xxxx xxxx xxxx xxxx xxxx pa...
45984        2  on main fin obtain cop credit report without p...
45987        2  review credit report ident inacc account appea...
46246        2  acc ask credit burea report correct problem ho...
46262        2  review credit report ident inacc account unaw ...
46535        3  receiv cal person claim investig xxxx xxxx xxx...
46700        3  synerget commun inc. say try collect account x...
46865        5  mr. coop purchas hom loan origin mortg company...
47053        2  xxxx report scor incorrect claim ow ex amount ...
48276        2  peopl rud paperwork loan didnt giv credit gap ...
49253        2  block exceiv otherw provid sect consum report ...
49321        2  follow account fraud xxxx 12000.00 xxxx xxxx x...
49412        2  xxxx xxxx not xxxx xxxx continu report fraud c...
50006        2  writ request remov unauth credit inquiry xx/xx...
50017        2  send inform ver disput sent follow-up disput x...
50147        2  id comprom misus benefit ins mobl auto fraud a...
50222        2  fraud account report credit report xxxx xxxx 5...
50419        2  im victim transun inquiry issu cal get inquiry...
50458        2  may concern complaint due unauth inquir transu...
50491        2  fraud account report credit report xxxx xxxx x...
50724        2  id comprom overs serv u.s. milit xxxx xxxx tim...
...        ...                                                ...
77212        2  transun xxxx xxxx show inquiry busy nev giv pe...
77214        4  xx/xx/xxxx leas agr xxxx xxxx xxxx sign us ban...
77216        5  mortg pay xxxx per mon paid xxxx xx/xx/xxxx xx...
77220        4  custom credit cent 2 year alway tre respect ho...
77224        3  xxxx xxxx xxxx collect ag keep cal sent let re...
77228        3  tim receiv bail bond mak pay year end los job ...
77234        2  xxxx delet bk pupl rcord xxxx xxxx cas xxxx re...
77236        1  xx/xx/2019 request mad onlin credit lin increa...
77238        1  xx/xx/19 paid bal credit card xxxx chas card 2...
77240        2  xxxx xxxx xx/xx/xxxx 9700.00 xxxx xxxx xx/xx/x...
77242        2  nee get nam straight credit report xxxx xxxx x...
77244        0  bmo har return check charg 36.00 first attempt...
77246        4  hello believ victim fraud phon cal regard stud...
77250        1  chas allow merch us card clos fraud charg cur ...
77254        2  writ request block inform credit fil fraud id ...
77258        2  contact nelnet xxxx regard past due account co...
77270        5  xx/xx/xxxx purchas property xxxx loan depot hi...
77274        3  receiv not debt disput leg remov bought anoth ...
77280        2  took loan hous citifin clos xx/xx/2320 sent xx...
77282        1  op cit doublecash card 0 promot off xx/xx/xxxx...
77284        5  problem n't quit occur yet 'm ward troubl n't ...
77286        2                                           id theft
77288        2  xxxx viol fcra fals report 4 invalid retail ac...
77290        2  xxxx xxxx credit card nev lat pay app charg xx...
77296        2  xx/xx/xxxx attempt plac temp thaw equifax cred...
77298        3  fcra stat inform report 100 ver 100 acc otherw...
77306        2  xxxx/xxxx submit cert let 3 credit burea xxxx ...
77308        2  writ request block inform credit fil fraud id ...
77316        3    xxxx tim school attend noth xxxx xxxx xxxx xxxx
77322        0  nam xxxx xxxx tri clos check account netspend ...

[5001 rows x 2 columns]

In [184]:
new_df.head()

       Product                                 Clenaed complaines
43374        3  cal dont answ cal cal day long hav sign contac...
44383        2  xxxx xxxx xxxx xxxx post 3 collect account 3 c...
44469        0  xxxx mon every mon sint xx/xx/2019 've reciev ...
44562        3  2 charg credit report collect ag `` trid asset...
44659        3  provid account inform show debt paid credit ka...

In [186]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_ids=TfidfVectorizer()
vector=tf_ids.fit_transform(new_df["Clenaed complaines"])

In [188]:
x_train=vector[1:4500].toarray()

In [190]:
y_train=df.iloc[1:4500,0]

In [193]:
x_test=vector[4500:].toarray()

In [194]:
y_test=df.iloc[4500:,0]

In [195]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
model= gnb.fit(x_train,y_train)

In [196]:
y_pred=gnb.predict(x_test)

In [197]:
from sklearn.metrics import classification_report

In [198]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.08      0.18      0.12        33
           1       0.37      0.33      0.35        57
           2       0.55      0.32      0.41       213
           3       0.38      0.46      0.42       111
           4       0.25      0.38      0.30        50
           5       0.39      0.43      0.41        37

   micro avg       0.36      0.36      0.36       501
   macro avg       0.34      0.35      0.33       501
weighted avg       0.42      0.36      0.37       501